# mongotools example to install mongo shell only
name: action-mongo-tools-exampleMongoShellOnly

on:
  workflow_dispatch:  # allow manual trigger only for example

jobs:
  mongo-tools-example-steps:
    runs-on: ubuntu-22.04

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Setup mongo tools - only mongo-shell
        uses: boly38/action-mongo-tools@stable
        with:
          mongo-tools: "false"

      - name: Mongo-shell usage - setup mongo user
        run: |
          mongosh --version
          mongosh admin --eval 'db.createUser({user:"root",pwd:"mypass",roles:[{"role":"readWrite","db":"myDbForTest"}, "restore"]});'